version: "3.9"

services:
  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    container_name: auth_service
    ports:
      - "8001:8001"
    volumes:
      - ./auth_service:/app        # hot-reload during dev
      - ./shared:/app/shared
    networks:
      - micro_shop_net

  product_service:
    build:
      context: .
      dockerfile: product_service/Dockerfile
    container_name: product_service
    ports:
      - "8002:8002"
    volumes:
      - ./product_service:/app     # hot-reload during dev
      - ./shared:/app/shared
    networks:
      - micro_shop_net
    depends_on:
      - auth_service

networks:
  micro_shop_net:
    driver: bridge
